# Generated by Django 5.2.13 on 2026-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0011_palco_acessibilidade_mobilidade_reduzida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palco",
            name="acessibilidade_mobilidade_reduzida",
            field=models.BooleanField(default=True),
        ),
    ]
